repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.12
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # Use a stable version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: pretty-format-json
        args: ["--autofix"]
      - id: check-merge-conflict
      - id: detect-private-key
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-symlinks
      - id: debug-statements
      - id: requirements-txt-fixer

  - repo: https://github.com/google/osv-scanner/
    rev: v2.0.2
    hooks:
      - id: osv-scanner
        args: ["-r", "."]
