repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: ["--fix"]
  
  # - repo: https://github.com/awslabs/automated-security-helper
  #   rev: v2.0.1        # ← pin the latest release tag
  #   hooks:
  #     - id: ash
  #       name: ash-security-scan
  #       manual: true  # Disable by default; run manually when needed
  #       args:
  #         # Fail the commit only on high/critical issues; report others
  #         - "--severity-threshold"
  #         - "high"
  #       # Run on all added/modified files by default
  #       types: [python]
  #       pass_filenames: true
