name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write
  checks: write
  issues: write
  pull-requests: write
  statuses: write


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          pip install poetry
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true
          poetry install --with dev
      - name: Run tests with coverage
        continue-on-error: true
        run: |
          poetry run pytest --cov=network_reputation_check --cov-report=xml --cov-report=term
      - name: Generate and Commit Coverage Badge
        run: |
          poetry run genbadge coverage -i coverage.xml -o coverage.svg
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add coverage.svg
          git diff --cached --quiet || git commit -m "Update coverage badge [ci skip]"
          git push || echo "No changes to push"

  lint:
    permissions:
      contents: read  # Restrict permissions to read-only
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          pip install poetry
          poetry config virtualenvs.create true
          poetry config virtualenvs.in-project true
          poetry install --with dev
      - name: Validate commit messages
        run: |
          poetry run cz check  # Validate commit messages against conventional commits
      - name: Run pre-commit hooks
        run: |
          poetry run pre-commit run --all-files
      - name: Commit changes made by hooks
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Apply pre-commit fixes [ci skip]" || echo "No changes to commit"
          git push || echo "No changes to push"
      - name: Run Super-Linter
        uses: github/super-linter@v7
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  validate-docker:
    permissions:
      contents: read  # Restrict permissions to read-only
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Validate build configuration
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_SUMMARY: true
        with:
          call: check
